version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/" # `.github/workflows`
      - "/.github/actions/*"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      chrono:
        patterns:
          - "chrono*"
      futures:
        patterns:
          - "futures*"
      openssl:
        patterns:
          - "openssl*"
      serde:
        patterns:
          - "serde*"
      tokio:
        patterns:
          - "tokio*"
      misc:
        patterns:
          - "askama*"
          - "base64*"
          - "bitflags"
          - "byteorder"
          - "directories"
          - "dirs"
          - "thiserror"
          - "toml"
          - "urlencoding"
          - "uuid"
          - "walkdir"
          - "whoami"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
